name: Moises
favicon: null
layout_spectrum: 0.31206077174283564
typography_spectrum: 0.4277495329733938
title: Inspired Living
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#125688'
    - '#a5a7aa'
    - '#c53535'
    - '#d8df3a'
  brandStrength: 0.5
  lightness: 0.5256108951289207
  saturation: 0.3879553347360343
  rhythmicContrast: 0.5
purpose: []
